include: package:flutter_lints/flutter.yaml

linter:
  rules:

web:
  experimental-hot-reload: true
  experimental-concurrent-js: true
  experimental-inline-js: true
  experimental-dart2js-optimizer: true
  experimental-web-compiler: true
  experimental-web-socket: true
  experimental-web-assembly: true
